name: mining
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^5.4.3
  firebase_database: ^11.1.4
  cloud_functions: ^5.1.3
  font_awesome_flutter: ^10.7.0
  persistent_bottom_nav_bar: ^6.2.1
  google_sign_in: ^6.2.1
  path_provider: ^2.1.4
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^27.1.52

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
